### ISSUE TITLE
Unused data/pages

### ISSUE THREAD

**Issue by JaxkDev** [mwilko/Mobile_Health_App#11]
Not sure what to do with the unused data pages:

- Heart Rate (saved, not used)
- Sleep (saved, not used)
- Nutrition (saved, not used)
- Cognition (saved, not used)
- MLA Exercise (saved, not used)

**Comment by mwilko** [comment]
Not sure about other pages, but i remember adding a score variable to Cognition which saves the amount of correct answers. Not sure how we would use it, just added it because we had no Cognitive functionality at all.

**Comment by summyre** [comment]
I'm working on the cognitive stuff atm so we can have at least something about it

**Comment by JaxkDev** [comment]
> Not sure about other pages, but i remember adding a score variable to Cognition which saves the amount of correct answers. Not sure how we would use it, just added it because we had no Cognitive functionality at all.

Ohhh I see, I was comparing User data didnt see it in the menu file 👍

**Comment by mwilko** [comment]
Yeah, i made a reset button too, just a case of figuring out what we can do, possibly add more pages for a bigger score  range? Then adding different score brackets? 

Cutting it close though.

**Comment by JaxkDev** [comment]
Yeah, check #12 
I'm trying to finish everything up code wise today and then start digging into report tomorrow.

Regards to these pages, I don't know.

My thoughts on this is:
Add the data to user (User.py) and leave it as a 'future feature',
as I have added a 'coming soon' label to Diabetes and Sleep disorder MLA's to say it can be expanded etc.

**Comment by JaxkDev** [comment]
Added all the listed pages to user data, so now everything functions and is saved.
Unaware to user not all is actually used, think that's all we can do now.
