### ISSUE TITLE
CODE DEADLINE - Tuesday 7th May 23:59

### ISSUE THREAD

**Issue by JaxkDev** [mwilko/Mobile_Health_App#12]
With the deadline in 168 Hours (7 days) from now, we need a deadline for the code so we can have time package up and do this youtube video too as well as confirm details for the report.

That said I'm thinking the below as a code deadline:
## **Tuesday 7th May 23:59**

giving us a day and a half to package, and do the video as well as final checks its all working.

NOTE: Tests for reports should be done ASAP not squeezed in after that date etc.
This deadline is simply to package and video up (releasing 1.0.0)

Please please please try and get all your bits checked in the code and any last changes done THIS WEEK, trying to finish code so everyone can then focus on final report :)

**Comment by JaxkDev** [comment]
Any change to deadline is welcome too, just a general idea of a 'code deadline'

**Comment by mwilko** [comment]
Sounds good Jack2.
