### ISSUE TITLE
BMI Float / Int

### ISSUE THREAD

**Issue by JaxkDev** [mwilko/Mobile_Health_App#14]
If you save the personal details, it will save as float and then put that float back into the boxes when you next visit the page but input validation fails when a float is in the input box

**Comment by mwilko** [comment]
Fixed, replaced float constraint with int.

**Comment by JaxkDev** [comment]
Still broken

**Comment by JaxkDev** [comment]
Just using my old data which was float, no worries.

**Comment by mwilko** [comment]
Was gunna say, was working on mine, haha.
